### ISSUE TITLE
Missing items

### ISSUE THREAD

**Issue by Schnieder6** [fuchsberger/lotd#14]
Finished checking in everything I have on my current playthrough. I found that the following were missing: Akaviri Katana, and silver dagger, mace, quarterstaff, shortspear, shortsword, spear, and trident.

In vanilla Skyrim, and my current LotD load order, Steel boots are steel cuffed boots. And steel gauntlets are steel nordic gauntlets, which _are_ included in this manager but currently have a [delete] tag in their name. I don't know if this is intentional or not.

Also not present, the Inn Soaps that have a display in the Safehouse with this mod https://www.nexusmods.com/skyrimspecialedition/mods/31144/

**Comment by Schnieder6** [comment]
Also steel shin boots are missing.

**Comment by fuchsberger** [comment]
Many thanks! I could really use more helpers like you!
I added all the missing silver weapons and fixed the remaining issues you mentioned (immersive armors renamed vanilla items that is why they appeared to be missing).

Innsoaps i have to wait for a list of soaps / wiki to update as i am not using the mod. If you have a complete list with the exact names i am happy to add them.

**Comment by fuchsberger** [comment]
inn soaps now also supported :)
