### ISSUE TITLE
Paintings

### ISSUE THREAD

**Issue by lordoozik** [fuchsberger/lotd#23]
so i had a look at the wiki and there it is listed that the east exhibit halls have 41 display for paintings yet your system only says that there are 40 paintings and even when i looked at the tcc total it says 93 and yours total is 92 so there must be 41 paintings in east exhibit halls. had a look in the game and didnt find the spot that was missing so look for yourself if you can.

**Comment by fuchsberger** [comment]
Thanks yeah when I made the list I also manually went through the museum and checked for painting holders. If you also couldn't find the missing spot then probably the wiki is inaccurate. If we end up finding it I will add it immediately. Thanks!
