### ISSUE TITLE
Site is down... Again.

### ISSUE THREAD

**Issue by 111222111** [fuchsberger/lotd#44]
As of this morning, the site told me that it was unavailable. Hoping that this can be fixed ASAP.

**Comment by fuchsberger** [comment]
I am working on some server stuff. apologies for the inconvenience.
hopefully back up in about two days

**Comment by 111222111** [comment]
Thank you for letting me know. I am using this to help keep track of the stuff I have in the museum, and it is a godsend.

**Comment by fuchsberger** [comment]
back online :)
LOTD Tool migrated again to a new domain (https://lotd.fly.dev/)
this allowed me to host the app for free and save on the server costs i have been paying for the last years
