### ISSUE TITLE
Paintings

### ISSUE THREAD

**Issue by darkequine** [fuchsberger/lotd#6]
This really isn't a bug or anything just some feedback. The paintings you have listed seem to be based off the v4 museum. I can't find any painting activators in the Library but I know there were several in the staircase that led to the safehouse in version 4.

The only paintings I know of right now in v5 are in the Hall of Heroes hallway, the East Exhibit Hall hallway, 2 in the safehouse and the 2 by the front door.

**Comment by fuchsberger** [comment]
thanks so much you are right I copied the info from the wiki. 
I'll have a walk through the museum tomorrow and take note of the new locations.

**Comment by fuchsberger** [comment]
All Paintings now fixed and 4 missing paintings accounted for!
